### ISSUE TITLE
Hex format type deduction by contents

### ISSUE THREAD

**Issue by Code7R** [TexZK/hexrec#33]
Hi,

the way how the current method hexrec.base.load (and its old hexrec implementation) decide about the file type is by analysing the filename. However, in practice, this is too limited. Sometimes you may receive data by a pure stream (wrapped via STringIO handle), sometimes the filename extension is misleading (i.e. .hex is used for other formats, like Srecord).

It would be good if the load method could either
1. let the user pass a file/stream handle into it (StringIO for hex data, BytesIO for the raw type) - then the user code decide the type beforehand, and do this cheaply (i.e. seeking the stream cursor to 0 after detecting the type)
2. do the content type detection inside (i.e. do the stream opening, checking, rewinding, would require the user to specify either a filename or some seek-supporting stream object, or reopening the file twice).

Or maybe a combination of both - keep the current code as is, and introduce a new variant in hexrec.base.FILE_TYPES called like "auto" which would perform the detection of user's input as in option 2.

What we did as a workaround is basically option 2 but manually from outside, it would be good to have this functionality inside.

Patches wanted?

Thanks a lot!

**Comment by TexZK** [comment]
Hi, I've just committed a draft onto the [`load_path_or_stream`](https://github.com/TexZK/hexrec/compare/main...load_path_or_stream) branch.

I made the `guess_format_name()` be just a guess, taking the first matching file extension, instead of trying to parse the file. It's just a quick guess, so that's enough for its purpose. I'm still using it to guess the output file type.

The `load()` global function now performs a brute-force file type detection, whenever the input format isn't explicit.
It still performs a quick guess at the beginning, in case the file extension matches (common case), then it tries every registered file type.

The load function now supports input streams. Whenever the brute-force attempt fails, the stream is rolled back to where it started parsing. As you pointed out, the stream must be seekable.

I also adjusted a few related functions and methods to support these changes, plus some test cases.

**Comment by TexZK** [comment]
Ah, a quick note about streams: I'm explicitly using byte streams only.

I tried with text streams in the past, but they quickly complicated the code base for almost no benefit, as the record file formats I encountered (also from other libraries) are either 100% ASCII-compliant or raw bytes.

If anybody wants to use text streams, they'd better access the underlying raw byte stream, like with `sys.stdin.buffer` and  `sys.stdout.buffer`, or build a wrapper stream (I'm not an expert on this topic).

**Comment by Code7R** [comment]
I need to check this later, will need a couple of days. By pure code review the changes look sound.

Yes, I also dislike text streams. They add too much ambiguity regarding encodings and line endings.

**Comment by Code7R** [comment]
A quick test almost worked but there might be an issue. Calling:

`
hexrec.base.load(None)
`

directly goes to 

base.py:373:

`
in_path = str(in_path_or_stream)
`

Which creates a string containing "None" and which causes  incorrect behavior with later none-type-checks.

**Comment by Code7R** [comment]
The last comment might be not correct. The argument of load() is not expected to handle None, thus I better give it `sys.stdin.buffer` which would be okay. Nevertheless, it would be good if there is an assertion so that if user sends None by mistake then the reason is shown immediately, avoiding this "None" confusion.

One thing which still makes me wonder: is  FILE_TYPES (MutableMapping) actually ordered? I cannot see the exact guarantee for that assumption even if it currently behaves that way. Because if it is not then the preference of a specific type is not guaranteed, and 'raw' might be randomly used instead of a specific type.

**Comment by TexZK** [comment]
I normally don't add special handlings for ``None`` nor for any undocumented special values to functions;
the caller should expect some exception at some point within their execution.

Anyway, since those `load()` and `save()` functions are high-level helper functions, I'll make `load(None)` remap to `sys.stdin.buffer` to help those who aren't exactly familiar (I myself discovered `.buffer` quite late).
This is symmetrical to what already implemented for `save()`.

Yes, `FILE_TYPES` has to be ordered, so I'm going to make the description explicit.

**Comment by TexZK** [comment]
Changes appended to the [load_path_or_stream](https://github.com/TexZK/hexrec/compare/main...load_path_or_stream) branch.

When all is looking good, I'm releasing version `0.4.2`.

**Comment by TexZK** [comment]
Hi, sorry for the late reply.

The `FILE_TYPES` is a global variable (a `MutableMapping` indeed), and as such the user is free to mess with it.
Such a mapping is required to be ordered; a standard `dict` would do the trick since Python 3.6 (I find `collections.OrderedDict` rather messy).
Thus, no explicit wrapper APIs should be required, as the user has full control over the mapping.

Maybe I'd better change it to lowercase `file_types`, since uppercase is expected for constants.

After this little change I'm going to release the changes.

**Comment by TexZK** [comment]
Changes added to commit 65177088f0b174c291a418b0f0e655eba61c399b
